#Author: Ha Le
#The test verify user can modify label on each character box

import Setup
def AdvOCR_CPM_016(): 
  Setup.Setup_InnitializeCPM()
  Setup.Setup_InnitializeVPM() 
  Setup.Setup_loadVPM()
  Setup.Setup_OCRImages()
  Setup.Setup_VPMNewButton()
  Setup.Setup_AdvOCR()
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_2.SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_2.SwingObject("JTextField", "", 0).Keys("[BS]1")
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_3.SwingObject("JLabel", "7", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_3.TextField2.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_3.TextField2.Keys("[BS]2")
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_4.SwingObject("JLabel", "a", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_4.Label2.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_4.Label2.Keys("[BS]3")
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_.SwingObject("JLabel", "l", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_.TextField.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_.TextField.Keys("[BS]4")
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_5.SwingObject("JLabel", "o", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_5.TextField.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_5.TextField.Keys("[BS]5")
  scrollPane = Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane
  #scrollPane.VScroll.Pos = 0
  scrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.VScroll.Pos = 133
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_6.SwingObject("JLabel", "t", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_6.TextField.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_6.TextField.Keys("[BS]6")
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_7.SwingObject("JLabel", "w", 1).Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_7.TextField.Click(True)
  Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.ScrollPane.Viewport.Panel.Panel.ToolSetupCardPanel.HOG_OCRSetup_HOGTrainPanel.Panel3.Panel.Panel.OCRSetPanel.ScrollPane.Viewport.OCRSetPanel_LibraryPanel_.OCRSetPanel_CharTemplatePanel_7.TextField.Keys("[BS]7")
  #Delay(1000)
 
  Setup.Setup_LoadCPM()
  #Regions.DisplayCanvas5.Check(Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.Panel.Panel.HOG_OCRSetup_HOG_OCRSetupPanel_2.ROIEditor.Panel.Panel.ScrollPane.Viewport.DisplayCanvas)
 # Regions.DisplayCanvas6.Check(Regions.CreateRegionInfo(Aliases.javaw.VpmFrame.RootPane.null_layeredPane.null_contentPane.VPM.HideableTabbedPane.SplitPane.DetailComponent.DetailComponent_1.DetailComponent_BottomComponent_.PropertiesTabbedPane.Panel.Setup.BaseSetupPanel_1.Panel.Panel.HOG_OCRSetup_HOG_OCRSetupPanel_2.ROIEditor.Panel.Panel.ScrollPane.Viewport.DisplayCanvas, 58, 94, 294, 131, False))

  Setup.Setup_DragOCRFontLibraryToCpFile()
  Setup.Setup_EnableRunMode()
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]t")
  Delay(200)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "2", 1).Click(True)
  #Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]e")
  Delay(200)
  #Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 2).SwingObject("JLabel", "3", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "3", 1).Click(True)
  
  #Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 2).SwingObject("JTextField", "", 0).Click
  
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]s")
  Delay(200)
  #Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JLabel", "4", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "4", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]t")
  Delay(200)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "5", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]o")
  Delay(300)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "6", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]c")
  Delay(300)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 1).SwingObject("JLabel", "7", 1).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Click(True)
  Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCRSet.OCRSetFrame.OCRSetDisplay.OCRSetPanel.ScrollPane.Viewport.SwingObject("OCRSetPanel$LibraryPanel_", "", 0).SwingObject("OCRSetPanel$CharTemplatePanel_", "", 0).SwingObject("JTextField", "", 0).Keys("[BS]r")
    
   
  Setup.Setup_DisableRunMode()  
  
  Regions.Control_GlassPane5.Check(Regions.CreateRegionInfo(Aliases.javaw.CpmFrame2.RootPane.null_layeredPane.null_contentPane.Panel.SplitPane.SplitPane.ScrollPane.Viewport.CpmFrame_25.Panel_1.OCR_Font_Library2.Search_Image.Control_GlassPane, 112, 113, 236, 71, False))
  
  Setup.Setup_closeCPM()
  Setup.Setup_closeVPM()



